"""
Common dependency providers.

Reusable dependencies shared across the application.
"""

from __future__ import annotations

from typing import Annotated

from fastapi import Header, Query, Request


# ---------------------------------------------------------------------
# Request Metadata
# ---------------------------------------------------------------------


def get_request_id(request: Request) -> str:
    """
    Return the request identifier generated by middleware.

    Returns:
        Request ID.
    """
    return getattr(request.state, "request_id", "")


RequestIdDependency = Annotated[
    str,
    Header(alias="X-Request-ID"),
]


# ---------------------------------------------------------------------
# Client Information
# ---------------------------------------------------------------------


def get_client_ip(request: Request) -> str:
    """
    Return the client's IP address.

    Returns:
        Client IP address.
    """
    if request.client is None:
        return "unknown"

    return request.client.host


# ---------------------------------------------------------------------
# Pagination
# ---------------------------------------------------------------------


def pagination_params(
    page: int = Query(
        default=1,
        ge=1,
    ),
    page_size: int = Query(
        default=20,
        ge=1,
        le=100,
    ),
) -> tuple[int, int]:
    """
    Standard pagination dependency.

    Returns:
        (page, page_size)
    """
    return page, page_size


PaginationDependency = Annotated[
    tuple[int, int],
    Query(),
]